### ISSUE TITLE
Small window widths hide the compose area

### ISSUE THREAD

**Issue by lf-** [sdras/productive-twitter#1]
To reproduce: make window narrow. The compose box at the top will disappear. My suspicion is that the compose button which is normally redundant (and was thus removed) isn't so when the window is below a certain width.

![image](https://user-images.githubusercontent.com/6652840/61595641-e1129600-abb6-11e9-9bfa-f84eee1d7604.png)

(I removed the timeline from the screenshot, that's not itself a bug)

**Comment by sdras** [comment]
Sorry, I'm not really interested in tracking this down and don't have the time to (please see README for more information). Please feel free to fork it, fix it, and host the extension locally though!
