### ISSUE TITLE
avatar in sidebar misaligned

### ISSUE THREAD

**Issue by SavePointSam** [sdras/productive-twitter#2]
The avatar next to the Profile menu option in the sidebar is misaligned.

![Screen Shot 2019-07-22 at 12 03 34 PM](https://user-images.githubusercontent.com/8203211/61657832-c143a680-ac78-11e9-9de2-acbeb591ba22.png)

**Comment by sdras** [comment]
I'm not sure I am seeing what you're seeing, but either way, it's not something that's bothering me that I'm likely to fix, you're welcome to fork it and host the extension locally though!
