### ISSUE TITLE
checkbox colors are off

### ISSUE THREAD

**Issue by SavePointSam** [sdras/productive-twitter#3]
The checkbox styles are being accidentally overridden causing previously light-colored boxes to appear dark.

![Screen Shot 2019-07-22 at 12 14 25 PM](https://user-images.githubusercontent.com/8203211/61658516-58f5c480-ac7a-11e9-859d-24940793e07f.png)

Twitter uses the following structure to define their checkbox UI.

```html
<div class="css-1dbjc4n r-1loqt21 r-1y8ork0 r-lrvibr">
  <div class="css-1dbjc4n r-sdzlij r-14u3nlf r-q81ovl r-o7ynqc r-6416eg">
    <div class="css-1dbjc4n r-1awozwy r-yfoy6g r-1778zho r-z2wwpe r-1phboty r-d045u9 r-76blku r-1777fci r-64lmo0"></div>
  </div>

  <input type="checkbox" data-focusable="true" class="r-1p0dtai r-1ei5mc7 r-1pi2tsx r-1d2f490 r-crgep1 r-orgf3d r-t60dpp r-u8s1d r-zchlnj r-ipm5af r-13qz1uu">
</div>
```

Given their computed classnames, it may be annoying to revert the style to work properly. The offending CSS is [here](https://github.com/sdras/productive-twitter/blob/master/override.css#L66-L68).

**Comment by sdras** [comment]
Fixed
