### ISSUE TITLE
Breaks if dark mode isn't turned on

### ISSUE THREAD

**Issue by ashutoshgngwr** [sdras/productive-twitter#5]
![2019-07-26-15-06-24](https://user-images.githubusercontent.com/7106123/61942482-20762380-afb7-11e9-9843-d3f3ccb2b6c8.png)

**Comment by Moorviper** [comment]
Yes as mentioned in the readme ...

**Comment by sdras** [comment]
Yep, that's the setting it's designed for. As mentioned in both the readme and the extension.
